# Python introduction

In [4]:
char_list='Hello'

In [5]:
print(char_list)

Hello


In [6]:
char_list[0]

'H'

# Arithmatic

Adds values on either side of the operator

In [99]:
a=10
b=20
a+b

30

Subtracts right hand operand from left hand operand.

In [100]:
b-a

10

Multiplies values on either side of the operator

In [101]:
a*b

200

Divides left hand operand by right hand operand

In [102]:
b/a

2

Divides left hand operand by right hand operand and returns remainder

In [103]:
b%a

0

Performs exponential (power) calculation on operators

In [104]:
b**2

400

# Comparison

If the values of two operands are equal, then the condition becomes true.

In [105]:
a==b

False

If values of two operands are not equal, then condition becomes true.

In [106]:
a!=b

True

If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.

In [108]:
a>=b

False

# List

List is a data structure in Python is the sequence. Each element of a sequence is assigned a number - its position or index. The first index is zero, the second index is one, and so forth.

In [21]:
list_num=[1,2,3,4,5]

In [9]:
list_num[0]

1

In [10]:
list_num[0:2]

[1, 2]

In [11]:
list_num[-1] 

5

In [21]:
range(1,5,1)

[1, 2, 3, 4]

# List Properties

In [74]:
fruits = ['orange', 'pear', 'banana', 'kiwi', 'apple']

In [75]:
fruits.append('banana')

In [76]:
fruits

['orange', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [77]:
fruits.remove('apple')

In [78]:
fruits

['orange', 'pear', 'banana', 'kiwi', 'banana']

In [79]:
fruits.index('pear')

1

In [80]:
fruits.sort()

In [89]:
fruits

['banana', 'banana', 'kiwi', 'orange', 'pear']

In [90]:
vegetables=['carrot','Pea','Onion','Potato']

In [92]:
grocery=fruits+vegetables

In [93]:
grocery

['banana',
 'banana',
 'kiwi',
 'orange',
 'pear',
 'carrot',
 'Pea',
 'Onion',
 'Potato']

# Set

A set is an unordered collection of items. Every element is unique (no duplicates) and must be mutable (which cannot be changed).

In [82]:
test_set=set(fruits)

In [83]:
test_set

{'banana', 'kiwi', 'orange', 'pear'}

In [84]:
test_set.add('apple')

In [85]:
test_set

{'apple', 'banana', 'kiwi', 'orange', 'pear'}

In [87]:
test_set.remove('kiwi')

In [88]:
test_set

{'apple', 'banana', 'orange', 'pear'}

In [95]:
set(fruits).union(set(vegetables))

{'Onion', 'Pea', 'Potato', 'banana', 'carrot', 'kiwi', 'orange', 'pear'}

In [96]:
set(grocery).difference(set(vegetables))

{'banana', 'kiwi', 'orange', 'pear'}

# Array

In general, numerical data arranged in an array-like structure in Python can be converted to arrays through the use of the array() function. 

In [1]:
import numpy as np

NumPy has built-in functions for creating arrays from scratch:

zeros(shape) will create an array filled with 0 values with the specified shape. The default dtype is float64.

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.array([2,3,1,0])

array([2, 3, 1, 0])

In [8]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [3]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Basic operation

In [5]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

In [6]:
b

array([0, 1, 2, 3])

In [11]:
a-b

array([20, 29, 38, 47])

In [13]:
b**2

array([0, 1, 4, 9])

In [14]:
a*b

array([  0,  30,  80, 150])

Two dimention

In [15]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Dictionary

Each key is separated from its value by a colon (:), the items are separated by commas, and the whole thing is enclosed in curly braces. An empty dictionary without any items is written with just two curly braces, like this: {}.

Keys are unique within a dictionary while values may not be. The values of a dictionary can be of any type, but the keys must be of an immutable data type such as strings, numbers, or tuples.

In [16]:
dic_test={'key1':1,'key2':2}

In [17]:
dic_test['key1']

1

In [18]:
list(dic_test.keys())

['key1', 'key2']

In [19]:
list(dic_test.values())

[1, 2]

# Loop

Loops are used when we want to repeat a function severl times. The Python for statement iterates over the members of a sequence in order, executing the block each time. 

In [22]:
for num in list_num:
    print(num)

1
2
3
4
5


In [24]:
for i in range(0, len(list_num)):
    print(list_num[i]+1)

2
3
4
5
6


In [29]:
x = 1
while x<5:
    print("Here is the new value of {}".format(x))
    x += 1

Here is the new value of 1
Here is the new value of 2
Here is the new value of 3
Here is the new value of 4


Nested Loop

In [31]:
for x in range(1, 3):
    for y in range(1, 3):
        print('{} * {} = {}'.format(x, y, x*y))

1 * 1 = 1
1 * 2 = 2
2 * 1 = 2
2 * 2 = 4


Early exit

In [32]:
for x in range(3):
    print(x)
    if x == 1:
        break

0
1


# Split

The method split() returns a list of all the words in the string, using str as the separator (splits on all whitespace if left unspecified), optionally limiting the number of splits to num.

In [33]:
test_split="here is the second week * of the course "

In [34]:
test_split.split("*")

['here is the second week ', ' of the course ']

# Regular expression

In [35]:
import re

Use + and * to specify repetition in the pattern

+ -- 1 or more occurrences of the pattern to its left, e.g. 'i+' = one or more i's
* -- 0 or more occurrences of the pattern to its left
? -- match 0 or 1 occurrences of the pattern to its left

Here are the most basic patterns which match single chars:


\w -- (lowercase w) matches a "word" character: a letter or digit or underbar [a-zA-Z0-9_]. Note that although "word" is the mnemonic for this, it only matches a single word char, not a whole word. \W (upper case W) matches any non-word character.

\b -- boundary between word and non-word

\s -- (lowercase s) matches a single whitespace character -- space, newline, return, tab, form [ \n\r\t\f]. \S (upper case S) matches any non-whitespace character.

\t, \n, \r -- tab, newline, return

\d -- decimal digit [0-9] (some older regex utilities do not support but \d, but they all support \w and \s)

^ = start, $ = end -- match the start or end of the string

\ -- inhibit the "specialness" of a character. So, for example, use \. to match a period or \\ to match a slash. If you are unsure if a character has special meaning, such as '@', you can put a slash in front of it, \@, to make sure it is treated just as a character.

Just keep Digit

In [36]:
re.sub(r'\D', "", "2004-959-559 # This is Phone Number")

'2004959559'

Remove everything except alphabet and espace

In [37]:
re.sub(r'[^a-zA-Z\s]', "", "2004-959-559 # This is Phone Number")

'  This is Phone Number'

Find pattern

In [38]:
re.sub(r'\w+\d\s*\d\s*\d\w+','DONE', ' This is the pattern we find to find .. xx1 2   3xx .. end of expression')

' This is the pattern we find to find .. DONE .. end of expression'

# Function

You can define functions to provide the required functionality. Here are simple rules to define a function in Python.

Function blocks begin with the keyword def followed by the function name and parentheses ( ( ) ).

Any input parameters or arguments should be placed within these parentheses. You can also define parameters inside these parentheses.

The first statement of a function can be an optional statement - the documentation string of the function or docstring.

The code block within every function starts with a colon (:) and is indented.

The statement return [expression] exits a function, optionally passing back an expression to the caller. A return statement with no arguments is the same as return None.

def functionname( parameters ):

   "function_docstring"
   
   function_suite
   
   return [expression]

In [39]:
def changeme( ll ):
   ll.append([1,2,3,4]);
   return

In [40]:
mylist = [10,20,30];
changeme( mylist );

In [41]:
mylist

[10, 20, 30, [1, 2, 3, 4]]

Function with several arguments

In [6]:
def printinfo( name, age ):
   print("Name: ", name)
   print("Age ", age)
   return;

Method 1

In [7]:
printinfo( name="miki",age=50 )

Name:  miki
Age  50


Method 2

In [44]:
printinfo("miki",50)

Name:  miki
Age  50


# Class

Classes provide a means of bundling data and functionality together. 

In [3]:
class Customer(object):
    def __init__(self, name, balance): 
        self.name = name
        self.balance = balance
        
    def withdraw(self, amount):
        if amount > self.balance:
            raise RuntimeError('Amount greater than available balance.')
        self.balance -= amount
        return self.balance

    def deposit(self, amount):
        self.balance += amount
        return self.balance

In [4]:
jeff = Customer('Jeff Knupp', 1000.0)

Self :  Self is the instance of the Customer that withdraw and deposit are being called on. 


__init__: we call __init__, we initialize objects.After __init__ has finished, the caller can rightly assume that the object is ready to use.

In [5]:
jeff.name

'Jeff Knupp'

In [118]:
jeff.withdraw(100.0)

900.0

jeff.withdraw(100.0) is just shorthand for Customer.withdraw(jeff, 100.0)