In [1]:
import tensorflow as tf

In [2]:
constant_A=tf.constant([100])
constant_B=tf.constant([300])
constant_C=tf.constant([3])

In [3]:
print(constant_A)

Tensor("Const:0", shape=(1,), dtype=int32)


In [4]:
res_sum=tf.add(constant_A,constant_B)
res_mul=tf.multiply(constant_A,constant_C)

In [5]:
with tf.Session() as sess:
    print(sess.run(constant_A))
    result = sess.run([res_sum,res_mul])
    print(result)
sess.close()

[100]
[array([400], dtype=int32), array([300], dtype=int32)]


# Rank 

In [6]:
scalar=tf.constant(100)
vector=tf.constant([1,2,3,4,5])
matrix=tf.constant([[1,2,3],[4,5,6]])
cub_matrix=tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])

In [7]:
print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cub_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


# Tensor convert from python object

In [8]:
import numpy as np
a1dim = np.array([1,2,3,4,5])
print("a1dim Shape : ",a1dim.shape)

a1dim Shape :  (5,)


In [9]:
tf_t=tf.convert_to_tensor(a1dim,dtype=tf.float64)
print('tf_t : ',tf_t)
with tf.Session() as sess:
    res=sess.run(tf_t)
    print(res)
    sess.close()


tf_t :  Tensor("Const_7:0", shape=(5,), dtype=float64)
[1. 2. 3. 4. 5.]


# Constant

In [10]:
a = tf.constant([2, 2], name="vector") 
b = tf.constant([[0, 1], [2, 3]], name="matrix")

In [11]:
c=tf.zeros([2, 3], tf.int32)
d=tf.zeros_like(b)
e=tf.ones([2,3], dtype=tf.float32, name=None)
f=tf.fill([2, 3], 5)
g=tf.linspace(10.0, 13.0, 4, name="whatever")

In [12]:
with tf.Session() as sess:
    res=sess.run(a)
    print(res)
    print('-------')
    res=sess.run(b)
    print(res)
    print('-------')
    res=sess.run(c)
    print(res)
    print('-------')
    res=sess.run(d)
    print(res)
    print('-------')
    res=sess.run(e)
    print(res)
    print('-------')
    res=sess.run(f)
    print(res)
    print('-------')
    res=sess.run(g)
    print(res)
    sess.close()

[2 2]
-------
[[0 1]
 [2 3]]
-------
[[0 0 0]
 [0 0 0]]
-------
[[0 0]
 [0 0]]
-------
[[1. 1. 1.]
 [1. 1. 1.]]
-------
[[5 5 5]
 [5 5 5]]
-------
[10. 11. 12. 13.]


# Variable

In [13]:
# Even statically allocated variables should be initialized

a = tf.Variable(222, name="scalar") 
b = tf.Variable([4, 6], name="vector")
c = tf.Variable([[1 ,2], [3, 4]], name="matrix")
d = tf.Variable(tf.zeros([7,5])) 

init_op = tf.global_variables_initializer()
print('Here is initializing:',init_op)

with tf.Session() as sess:
    sess.run(init_op)
    res=sess.run(a)
    print(res)
    print('-------')
    res=sess.run(b)
    print(res)
    print('-------')
    res=sess.run(c)
    print(res)
    print('-------')
    res=sess.run(d)
    print(res)
    sess.close()

Here is initializing: name: "init"
op: "NoOp"
input: "^scalar/Assign"
input: "^vector_1/Assign"
input: "^matrix_1/Assign"
input: "^Variable/Assign"

222
-------
[4 6]
-------
[[1 2]
 [3 4]]
-------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In TensorFlow the differences between constants and variables are that :
Constant:
1-when you declare some constant, its value can't be changed in the future. 
2-The initialization should be with a value, not with operation.

Variable:
1-You can change its value in the future with tf.assign() method.
2-The initialization can be achieved with a value or operation.


In [24]:
x = tf.constant(35, name='x')
y = tf.Variable(x + 5, name='y')

model = tf.global_variables_initializer() 

with tf.Session() as session:
    session.run(model)
    print(session.run(y))
    sess.close()

40


In [ ]:
# This code can not be execute as the constant can not be defined as variable
x = tf.constant(35, name='x')
y = tf.constant(x + 5, name='y')

with tf.Session() as session:
    print(session.run(x))
    print(session.run(y))
    sess.close()

# Input and Reader

In [47]:
a = tf.constant([5, 5, 5], tf.float32, name='A')

b = tf.placeholder(tf.float32, shape=[3], name='B')

c = tf.add(a, b, name="Add")

with tf.Session() as sess:
    # create a dictionary:
    d = {b: [1, 2, 3]}
    # feed it to the placeholder
    res=sess.run(c, feed_dict=d)
    print(res)

[6. 7. 8.]
